### ISSUE TITLE
pip2 does not collect webthing

### ISSUE THREAD

**Issue by novski** [mozilla-iot/webthing-python#42]
i get errors when pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7) collects webthing on Raspberrypi 3B+:

```
pi@testpi:~ $ pip install webthing
Collecting webthing
  Downloading https://files.pythonhosted.org/packages/81/2a/056733afd4c70e20a4ad6fe0529677f5c5fce8fa0170702f5cb55422bb2e/webthing-0.11.1.tar.gz
Collecting jsonschema (from webthing)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```

**Comment by mrstegeman** [comment]
Looks like a network error with pip.

**Comment by novski** [comment]
Isn't this a dependencies problem? Like that the jsonschema dependencie does not work with python2.7 or so?
jsonschema is the first line in 'requirements' of setup.py.

```
requirements = [
    'jsonschema',
    'netifaces',
    'pyee',
    'tornado',
    'zeroconf',
]
```

**Comment by novski** [comment]
strange, in a virtualenv it works.
![bildschirmfoto 2019-01-29 um 12 32 22](https://user-images.githubusercontent.com/6088056/51905625-01108c00-23c2-11e9-940d-7598c920a83e.png)

do you know how to find out why?

**Comment by novski** [comment]
Please excuse. it works like a charm. 
I must have had network problems then... 
You can close this. Thanks a lot for your attention.

**Comment by mrstegeman** [comment]
No problem, glad it’s working.
